typography_spectrum: 0.26598627818748355
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7929399511776865
  lightness: 0.7495053708553314
  saturation: 0.6393185714259744
  rhythmicContrast: 0.014979226747527719
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8960772913414985
analytics:
  google: null
  facebook: null
  twitter: null
name: HCPN Trucking
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Hey,... it''s me.'
    url: 'https://www.facebook.com/densermania'
    type: external
favicon: null
purpose: []
