name: HCPN Trucking
favicon: null
layout_spectrum: 0.8960772913414985
typography_spectrum: 0.26598627818748355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7929399511776865
  lightness: 0.7495053708553314
  saturation: 0.6393185714259744
  rhythmicContrast: 0.014979226747527719
purpose: []
